spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/recondb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  server:
    port: 8080
  devtools:
    add-properties: false
    restart:
      enabled: false
  logging:
    level:
      root: INFO
      org.springframework: DEBUG